### ISSUE TITLE
Correction semaine 4

### ISSUE THREAD

**Issue by MathieuHoude** [saadeddinne/saadeddinne-Rocket_Elevators_Information_System#21]
Excellent travail! Tout est fonctionnel et vous fait un excellent boulot pour le visuel. Très bonne idée la section Profile pour un user générique. Tous les champs du quote sont sauvegardés dans la base de données comme il se doit, et le formulaire fonctionne très bien.
Le code lui-même est très bon aussi, c'était une bonne idée d'y aller avec les partials pour vos pages.
J'aime ce que vous avez fait pour votre readme, ça fait pro. Certains liens dans le haut ne fonctionnent pas par contre!

Quelques suggestions:

- Je vois que avez changé un peu le design de rails admin, c'est une très bonne idée. J'aurais essayé de garder l'esthétique de Rocket Elevators (les couleurs notamment).
- Vous avez fait une bonne job pour limiter l'accès de la section admin aux employés et pas aux autres users. Bien que l'on n'ait pas l'option d'y accéder, on peut toujours entrer l'URL et tenter d'y accéder. On tombe alors sur un écran rouge de Rails. Idéalement, ce serait de rediriger vers une autre page ou quelque chose du genre. C'est un détail bien sûr, pas de points perdus pour ça.
- Petit détail vraiment dommage... Assurez vous d'avoir le nom exact demandé pour votre repo!
- Il semble y avoir des colonnes en double pour les quotes (exemple Totalcost vs Total)?

Voilà, excellent travail, continuez comme ça!

**Comment by saadeddinne** [comment]
Bonjour, 
Au nom de mon équipe, merci beaucoup pour vos commentaires. On va corriger les problèmes mentionnées et on va prendre en considération vos suggestions pour avoir une deuxième version plus optimise.
